[build]
  # Build command for Vite
  command = "npm run build"
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

[dev]
  command = "vite --host 0.0.0.0 --port 3000"
  targetPort = 3000
  port = 8889
  functions = "netlify/functions"
  autoLaunch = false

# API endpoints are automatically mapped to function files by Netlify
# /api/login -> netlify/functions/login.js
# /api/register -> netlify/functions/register.js  
# /api/me -> netlify/functions/me.js
# /api/save -> netlify/functions/save.js
# /api/health/db -> netlify/functions/health-db.js

# Auth endpoints
[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/me"
  to = "/.netlify/functions/me"
  status = 200

[[redirects]]
  from = "/api/save"
  to = "/.netlify/functions/save"
  status = 200

[[redirects]]
  from = "/api/health/db"
  to = "/.netlify/functions/health-db"
  status = 200

[[redirects]]
  from = "/api/db-test"
  to = "/.netlify/functions/db-test"
  status = 200

# Chat endpoints
[[redirects]]
  from = "/api/chat/*"
  to = "/.netlify/functions/chat/:splat"
  status = 200

# Market endpoints
[[redirects]]
  from = "/api/market/*"
  to = "/.netlify/functions/market/:splat"
  status = 200

# Only redirect paths that don't have file extensions (SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {extensions = ["!css", "!js", "!png", "!jpg", "!jpeg", "!gif", "!svg", "!ico", "!woff", "!woff2", "!ttf", "!eot"]}

# Headers for security and CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, DELETE"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (set these in Netlify dashboard)
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_ANON_KEY = "your-supabase-anon-key"
# SUPABASE_SERVICE_ROLE_KEY = "your-supabase-service-role-key"
# JWT_SECRET = "your-jwt-secret"